#! /bin/bash
#
# Author: Armando Basile, 2013
#
# Please send feedback to armando@integrazioneweb.com
#
# /etc/init.d/sagentd
#
### BEGIN INIT INFO
# Provides: sagentd
# Required-Start: $local_fs $network $remote_fs
# Should-Start:
# Required-Stop: $local_fs $network $remote_fs
# Should-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 2 6
# Short-Description: Agent for sensors
# Description:    Runs up the agent to manage sensors
### END INIT INFO

# Source function library.
#. /etc/rc.d/init.d/functions

SCRIPT_FILE="/run/media/armando/DEVDRIVE/sviluppo/python/sagent_solution/engine/agent.py"
#SCRIPT_FILE="/var/sagent/agent.py"
PID_FILE="/var/run/sagent.pid"


# start engine
start() {
    # Check if service is already running
    if [ -f $PID_FILE ]
    then
        # Restart request
        restart
    else
        echo "Starting Server Sagent "    
        # Start the daemon
        python $SCRIPT_FILE start
        echo
        return $?
        #exit $?
    fi
}



# stop engine
stop() {
    if [ -f $PID_FILE ]
    then
        # Stopping request
        echo "Stopping Server Sagent "
        # Stop the daemon
        python $SCRIPT_FILE stop
        echo
        return $?
        #echo
    else
        # nothing
        echo "Server Sagent already stopped"
    fi
}



# restart engine
restart() {
    stop
    sleep 4 # required for socket server thread
    start
}



# check engine status
status() {
	if [ -f $PID_FILE ]
	then
		echo "Server Sagent is enabled"
	else
		echo "Server Sagent is disabled"
	fi
    return 0
}



case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
	;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/sagentd {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $?
